server:
  servlet:
    context-path: /
  port: 8002
spring:
  rabbitmq:
    addresses: 192.168.43.7:5672
    username: root
    password: root
    virtual-host: /
    connection-timeout: 15000
    listener:          # 表示消费者消费成功消息以后需要手工的进行签收（ack），默认为auto
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1


