spring:
  rabbitmq:
    addresses: 192.168.43.7:5672
    username: root
    password: root
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true   # 使用启用消息确认模式
    publisher-returns: true   # 设置return消息模式，注意要和 template.mandatory 配置配合使用
    template:
      mandatory: true   # 该配置需要与 publisher-returns 配合使用

# 配置对应的端口号
server:
  port: 8001

